### ISSUE TITLE
Add configuration parameter to allow disabling gc_pause metrics

### ISSUE THREAD

**Issue by TheNavigat** [michaelwittig/node-heap-gc-cloudwatch#8]
Hey there,

It would be awesome if there was a configuration parameter we could configure to disable `gc_pause` metrics.

Thanks!

**Comment by vdavid** [comment]
Just a friendly ping on this one. Any tips to make `gc_pause` possible to turn off? I'm happy to do the change myself and send a PR, but I'm not familiar with the project's architecture, don't want to mess things up.

**Comment by michaelwittig** [comment]
@vdavid feel free to open a PR. A `config` object already exists.
